<?xml version="1.0" ?>
<robot name="vecloc" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="length1" value="1.0"/>
  <xacro:property name="length2" value="0.5"/>

  <!-- Used for fixing robot to world -->
  <link name="world"/>

  <joint name="base_rot" type="revolute">
    <parent link="world"/>
    <child link="base_link"/>
    <axis xyz="0 1 0" />
    <limit lower="-1.57" upper="1.57" effort="0.5293" velocity="6.159937255" />
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 ${length1/2} 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder radius="0.02" length="${length1}" />
      </geometry>
      <material name="green">
        <color rgba="0 .8 0 1" />
      </material>
    </visual>
  </link>

  <joint name="joint0" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 ${length1/2} 0" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit lower="-1.57" upper="1.57" effort="0.5293" velocity="6.159937255" />
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${length2/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.02" length="${length2}" />
      </geometry>
      <material name="green">
        <color rgba="0 .8 0 1" />
      </material>
    </visual>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link2"/>
    <origin xyz="0 ${length1} 0" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit lower="-1.57" upper="1.57" effort="0.5293" velocity="6.159937255" />
    <mimic joint="joint0" multiplier="1" offset="0" />
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${length2/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.02" length="${length2}" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 .8 1" />
      </material>
    </visual>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link3"/>
    <origin xyz="0 0 ${length2}" rpy="0 0 0" />
    <axis xyz="1 0 0" />
    <limit lower="-1.57" upper="1.57" effort="0.5293" velocity="6.159937255" />
    <mimic joint="joint0" multiplier="-1" offset="0" />
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 ${length1/2} 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder radius="0.02" length="${length1}" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 .8 1" />
      </material>
    </visual>
  </link>


</robot>
